version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - SQLALCHEMY_DATABASE_URI=sqlite:///data/puzzle_data.db
    restart: unless-stopped
